:sparkles: real music
Trampss/cycle-music pull request #16
Opened 2017-05-06 12:04 UTC by guillaumecrespel

Add library to play real music => https://github.com/keithwhor/audiosynth

rythmbox Playing by character and not by instrument, because, the instrument changed by the character.

2017-05-06 16:25 UTC, fabienjuif commented on public/audiosynth.js
> +var Synth, AudioSynth, AudioSynthInstrument;
Do you search for this lib on npm ?

2017-05-06 16:26 UTC, fabienjuif commented on src/components/rythmbox/rythmbox.js
> +  'C', // E
Delete commentaries

2017-05-06 16:26 UTC, fabienjuif commented on src/components/rythmbox/rythmbox.js
> +const characters = [
We should pass this from props to avoid duplication

2017-05-06 16:27 UTC, fabienjuif commented on src/drivers/music.js
> +      const { instrument, note, time = 2 } = music
We should delete default value as we argue before

2017-05-06 16:27 UTC, fabienjuif requested changes
Nice, some minors commentaries

2017-05-06 18:00 UTC, guillaumecrespel commented on public/audiosynth.js
> +var Synth, AudioSynth, AudioSynthInstrument;
this lib is not present on npm, and i don't find equivalent

2017-05-06 19:58 UTC, fabienjuif commented on public/audiosynth.js
> +var Synth, AudioSynth, AudioSynthInstrument;
We should fork it (https://github.com/keithwhor/audiosynth) and publish it.
So we can import it trough webpack

2017-05-07 09:00 UTC, guillaumecrespel commented on public/audiosynth.js
> +var Synth, AudioSynth, AudioSynthInstrument;
Just for that ? it's one file, and i think, we don't maintain this lib ?

2017-05-07 12:56 UTC, fabienjuif commented on src/components/speaker/speaker.js
> +    .startWith({ stop: true }).debug()
debug

2017-05-07 12:57 UTC, fabienjuif commented on src/components/rythmbox/rythmbox.js
> +    .map(characters => characters.map(c => isolate(Range, c.name)({
I prefer to map in two instructions, I find it easier to read and explain

2017-05-07 12:57 UTC, fabienjuif commented on src/drivers/music.js
> +      // eslint-disable-next-line no-undef
We cand delete the eslint-disable, I forgot it

2017-05-07 13:22 UTC, fabienjuif commented on src/components/rythmbox/rythmbox.js
> +const notes = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
Merge the other PR then move this into the config file ?

2017-05-07 13:23 UTC, fabienjuif approved these changes

2017-05-07 13:44 UTC, merged